server:
  port: 8084

spring:
  application:
    name: OWNER-SERVICE
  data:
    mongodb:
      host: localhost
      port: 27017
      database: users
    
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
