
server:
  port: 8083

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: users
      spring:
cloud:
    gateway:
      routes:
      - id: review
        uri: http://localhost:8030/
        predicates:
        - Path=/review/**


