
server:
  port: 8000

spring:
  data:
    mongodb:
      host: localhost
      database: users
      port: 27017
  application:
    name: USER-SERVICE
      
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
 
