
server:
  port: 9070

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: my-blog
      
  mail:
    host: smtp.gmail.com
    port: 587
    username: jrrchowdary9821@gmail.com
    password: zphkfkmzcizfrlrb
    
    properties:
      mail:
        smtp:
          auth: true
          starttls:
              enable: true

      


