
server:
  port: 9999


logging:
  level:
    root: info

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
#
##      CORS POLICY CONFIG
#      globalcors:
#        add-to-simple-url-handler-mapping: true
#
#        cors-configurations:
#          '[/**]':
#            allowedOrigins: "*"
#            allowedMethods:
#              - GET
#              - POST
#              - PUT
#              - DELETE
#              - PATCH
#
#            allowedHeaders:
#              - "Origin"
#              - "Content-Type"
#              - "Accept"
#              - "Authorization"
#              - "User-Key"
#              - "Request-Tracker"
#              - "Session-Tracker"
#              - "X-XSRF-TOKEN"
#              - "X-IBM-CLIENT-ID"
#              - "Message-ID"
#              - "X-IBM-CLIENT-SECRET"
#      default-filters:
#        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin, RETAIN_FIRST
#
#      httpserver:
#        wiretap: true
#      httpclient:
#        wiretap: true
#
##        SSL CONFIG
#        ssl:
#          use-insecure-trust-manager: true

#      ROUTES FEATURE
      routes:

#        BLOG MICROSERVICE ROUTE
        - id: BLOG-SERVICE
          uri: http://localhost:9000
          predicates:
            - Path=/blog/**

##        REVIEW MICROSERVICE ROUTE
#        - id: REVIEW-SERVICE
#          uri:
#          predicates:
#            - Path=
#
##        USER MICROSERVICE ROUTE
#        - id: USER-SERVICE
#          uri:
#          predicates:
#            - Path=
#
##        ADMIN MICROSERVICE ROUTE
#        - id: ADMIN-SERVICE
#          uri:
#          predicates:
#            - Path=
#
##        OWNER MICROSERVICE ROUTE
#        - id: OWNER-SERVICE
#          uri:
#          predicates:
#            - Path=
#
##        OTP MICROSERVICE ROUTE
#        - id: OTP-SERVICE
#          uri:
#          predicates:
#            - Path=
#
##        SUBSCRIBE MICROSERVICE ROUTE
#        - id: SUBSCRIBE-SERVICE
#          uri:
#          predicates:
#            - Path=