
server:
  port: 9000

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: my-blog
  application:
    name: BLOG-SERVICE
      
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost


      


