server:
  port: 9080

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: my-blog
      

logging:
  level:
    root: info
  pattern:
    file:  "%d{yyyy-MM-dd HH:mm:ss} [%thread] %logger{36} %-5level - %msg%n" 
  file:
    name: ./App.log